# Generated by Django 3.0.4 on 2020-04-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(default='Enter A Description', max_length=500),
        ),
    ]
