# Generated by Django 3.0.4 on 2020-04-18 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200418_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
