# Generated by Django 3.0.4 on 2020-04-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_classroom_description'),
        ('main_app', '0006_auto_20200418_0124'),
    ]

    operations = [
    ]
